-- Neovim/LazyVim Keybindings Cheatsheet
-- A comprehensive, curated list of keybindings for learning and reference.
-- Used by both the Neovim Snacks picker and the desktop walker menu.

local M = {}

M.keybindings = {
  -- General
  { mode = "Normal", category = "General", keys = "<leader>K", desc = "Keybindings Cheatsheet (this menu)" },
  { mode = "Normal", category = "General", keys = "<leader>fn", desc = "New file" },
  { mode = "Normal", category = "General", keys = "<leader>l", desc = "Lazy" },
  { mode = "Normal", category = "General", keys = "<leader>qq", desc = "Quit all" },
  { mode = "Normal", category = "General", keys = "<leader>ub", desc = "Toggle background" },
  { mode = "Normal", category = "General", keys = "<leader>uc", desc = "Toggle conceal" },
  { mode = "Normal", category = "General", keys = "<leader>ud", desc = "Toggle diagnostics" },
  { mode = "Normal", category = "General", keys = "<leader>uf", desc = "Toggle format on save" },
  { mode = "Normal", category = "General", keys = "<leader>uI", desc = "Toggle indent guides" },
  { mode = "Normal", category = "General", keys = "<leader>ul", desc = "Toggle line numbers" },
  { mode = "Normal", category = "General", keys = "<leader>uL", desc = "Toggle relative line numbers" },
  { mode = "Normal", category = "General", keys = "<leader>un", desc = "Dismiss all notifications" },
  { mode = "Normal", category = "General", keys = "<leader>sn", desc = "Notification history" },
  { mode = "Normal", category = "General", keys = "<leader>us", desc = "Toggle spelling" },
  { mode = "Normal", category = "General", keys = "<leader>uT", desc = "Toggle treesitter highlight" },
  { mode = "Normal", category = "General", keys = "<leader>uw", desc = "Toggle word wrap" },

  -- Navigation
  { mode = "Normal", category = "Navigation", keys = "h", desc = "Move left" },
  { mode = "Normal", category = "Navigation", keys = "j", desc = "Move down" },
  { mode = "Normal", category = "Navigation", keys = "k", desc = "Move up" },
  { mode = "Normal", category = "Navigation", keys = "l", desc = "Move right" },
  { mode = "Normal", category = "Navigation", keys = "w", desc = "Next word" },
  { mode = "Normal", category = "Navigation", keys = "W", desc = "Next WORD" },
  { mode = "Normal", category = "Navigation", keys = "b", desc = "Previous word" },
  { mode = "Normal", category = "Navigation", keys = "B", desc = "Previous WORD" },
  { mode = "Normal", category = "Navigation", keys = "e", desc = "End of word" },
  { mode = "Normal", category = "Navigation", keys = "E", desc = "End of WORD" },
  { mode = "Normal", category = "Navigation", keys = "0", desc = "Start of line" },
  { mode = "Normal", category = "Navigation", keys = "^", desc = "First non-blank character" },
  { mode = "Normal", category = "Navigation", keys = "$", desc = "End of line" },
  { mode = "Normal", category = "Navigation", keys = "gg", desc = "Go to first line" },
  { mode = "Normal", category = "Navigation", keys = "G", desc = "Go to last line" },
  { mode = "Normal", category = "Navigation", keys = "{", desc = "Previous paragraph" },
  { mode = "Normal", category = "Navigation", keys = "}", desc = "Next paragraph" },
  { mode = "Normal", category = "Navigation", keys = "%", desc = "Jump to matching bracket" },
  { mode = "Normal", category = "Navigation", keys = "f", desc = "Find char forward" },
  { mode = "Normal", category = "Navigation", keys = "F", desc = "Find char backward" },
  { mode = "Normal", category = "Navigation", keys = "t", desc = "Till char forward" },
  { mode = "Normal", category = "Navigation", keys = "T", desc = "Till char backward" },
  { mode = "Normal", category = "Navigation", keys = ";", desc = "Repeat last f/F/t/T" },
  { mode = "Normal", category = "Navigation", keys = ",", desc = "Reverse last f/F/t/T" },
  { mode = "Normal", category = "Navigation", keys = "H", desc = "Top of window" },
  { mode = "Normal", category = "Navigation", keys = "M", desc = "Middle of window" },
  { mode = "Normal", category = "Navigation", keys = "L", desc = "Bottom of window" },
  { mode = "Normal", category = "Navigation", keys = "<C-u>", desc = "Half page up" },
  { mode = "Normal", category = "Navigation", keys = "<C-d>", desc = "Half page down" },
  { mode = "Normal", category = "Navigation", keys = "<C-b>", desc = "Page up" },
  { mode = "Normal", category = "Navigation", keys = "<C-f>", desc = "Page down" },
  { mode = "Normal", category = "Navigation", keys = "zz", desc = "Center screen on cursor" },
  { mode = "Normal", category = "Navigation", keys = "zt", desc = "Scroll cursor to top" },
  { mode = "Normal", category = "Navigation", keys = "zb", desc = "Scroll cursor to bottom" },

  -- Editing
  { mode = "Normal", category = "Editing", keys = "i", desc = "Insert before cursor" },
  { mode = "Normal", category = "Editing", keys = "I", desc = "Insert at start of line" },
  { mode = "Normal", category = "Editing", keys = "a", desc = "Append after cursor" },
  { mode = "Normal", category = "Editing", keys = "A", desc = "Append at end of line" },
  { mode = "Normal", category = "Editing", keys = "o", desc = "Open new line below" },
  { mode = "Normal", category = "Editing", keys = "O", desc = "Open new line above" },
  { mode = "Normal", category = "Editing", keys = "x", desc = "Delete character under cursor" },
  { mode = "Normal", category = "Editing", keys = "X", desc = "Delete character before cursor" },
  { mode = "Normal", category = "Editing", keys = "r", desc = "Replace single character" },
  { mode = "Normal", category = "Editing", keys = "R", desc = "Enter replace mode" },
  { mode = "Normal", category = "Editing", keys = "s", desc = "Substitute character" },
  { mode = "Normal", category = "Editing", keys = "S", desc = "Substitute line" },
  { mode = "Normal", category = "Editing", keys = "c", desc = "Change (operator)" },
  { mode = "Normal", category = "Editing", keys = "C", desc = "Change to end of line" },
  { mode = "Normal", category = "Editing", keys = "cc", desc = "Change entire line" },
  { mode = "Normal", category = "Editing", keys = "d", desc = "Delete (operator)" },
  { mode = "Normal", category = "Editing", keys = "D", desc = "Delete to end of line" },
  { mode = "Normal", category = "Editing", keys = "dd", desc = "Delete entire line" },
  { mode = "Normal", category = "Editing", keys = "yy", desc = "Yank (copy) line" },
  { mode = "Normal", category = "Editing", keys = "p", desc = "Paste after cursor" },
  { mode = "Normal", category = "Editing", keys = "P", desc = "Paste before cursor" },
  { mode = "Normal", category = "Editing", keys = "J", desc = "Join line below" },
  { mode = "Normal", category = "Editing", keys = "u", desc = "Undo" },
  { mode = "Normal", category = "Editing", keys = "<C-r>", desc = "Redo" },
  { mode = "Normal", category = "Editing", keys = "~", desc = "Toggle case" },
  { mode = "Normal", category = "Editing", keys = "gU", desc = "Make uppercase (operator)" },
  { mode = "Normal", category = "Editing", keys = "gu", desc = "Make lowercase (operator)" },
  { mode = "Normal", category = "Editing", keys = ">>", desc = "Indent right" },
  { mode = "Normal", category = "Editing", keys = "<<", desc = "Indent left" },
  { mode = "Normal", category = "Editing", keys = ".", desc = "Repeat last edit" },
  { mode = "Visual", category = "Editing", keys = "d", desc = "Delete selection" },
  { mode = "Visual", category = "Editing", keys = "c", desc = "Change selection" },
  { mode = "Visual", category = "Editing", keys = "y", desc = "Yank selection" },

  -- Visual
  { mode = "Normal", category = "Navigation", keys = "v", desc = "Visual mode character-wise" },
  { mode = "Normal", category = "Navigation", keys = "V", desc = "Visual mode line-wise" },
  { mode = "Normal", category = "Navigation", keys = "<C-v>", desc = "Visual block mode" },

  -- Search
  { mode = "Normal", category = "Search", keys = "/", desc = "Search forward" },
  { mode = "Normal", category = "Search", keys = "?", desc = "Search backward" },
  { mode = "Normal", category = "Search", keys = "n", desc = "Next search match" },
  { mode = "Normal", category = "Search", keys = "N", desc = "Previous search match" },
  { mode = "Normal", category = "Search", keys = "*", desc = "Search word under cursor forward" },
  { mode = "Normal", category = "Search", keys = "#", desc = "Search word under cursor backward" },

  -- Text Objects
  { mode = "Operator", category = "Text Objects", keys = "iw", desc = "Inner word" },
  { mode = "Operator", category = "Text Objects", keys = "aw", desc = "A word" },
  { mode = "Operator", category = "Text Objects", keys = "i\"", desc = "Inner quotes" },
  { mode = "Operator", category = "Text Objects", keys = "a\"", desc = "Around quotes" },
  { mode = "Operator", category = "Text Objects", keys = "i(", desc = "Inner parentheses" },
  { mode = "Operator", category = "Text Objects", keys = "a(", desc = "Around parentheses" },
  { mode = "Operator", category = "Text Objects", keys = "i{", desc = "Inner braces" },
  { mode = "Operator", category = "Text Objects", keys = "a{", desc = "Around braces" },
  { mode = "Operator", category = "Text Objects", keys = "it", desc = "Inner tag" },
  { mode = "Operator", category = "Text Objects", keys = "at", desc = "Around tag" },
  { mode = "Operator", category = "Text Objects", keys = "ip", desc = "Inner paragraph" },
  { mode = "Operator", category = "Text Objects", keys = "ap", desc = "Around paragraph" },
  { mode = "Operator", category = "Text Objects", keys = "is", desc = "Inner sentence" },
  { mode = "Operator", category = "Text Objects", keys = "as", desc = "Around sentence" },
  { mode = "Operator", category = "Text Objects", keys = "iB", desc = "Inner block" },
  { mode = "Operator", category = "Text Objects", keys = "aB", desc = "Around block" },

  -- Marks
  { mode = "Normal", category = "Marks", keys = "m{a-z}", desc = "Set mark" },
  { mode = "Normal", category = "Marks", keys = "'{a-z}", desc = "Go to mark (line)" },
  { mode = "Normal", category = "Marks", keys = "`{a-z}", desc = "Go to mark (exact)" },

  -- Registers
  { mode = "Normal", category = "Registers", keys = "\"{a-z}y", desc = "Yank to register" },
  { mode = "Normal", category = "Registers", keys = "\"{a-z}d", desc = "Delete to register" },
  { mode = "Normal", category = "Registers", keys = "\"{a-z}p", desc = "Paste from register" },
  { mode = "Insert", category = "Registers", keys = "<C-r>{reg}", desc = "Insert from register" },

  -- Macros
  { mode = "Normal", category = "Macros", keys = "q{a-z}", desc = "Record macro" },
  { mode = "Normal", category = "Macros", keys = "@{a-z}", desc = "Play macro" },
  { mode = "Normal", category = "Macros", keys = "@@", desc = "Repeat last macro" },

  -- Folds
  { mode = "Normal", category = "Folds", keys = "za", desc = "Toggle fold" },
  { mode = "Normal", category = "Folds", keys = "zc", desc = "Close fold" },
  { mode = "Normal", category = "Folds", keys = "zo", desc = "Open fold" },
  { mode = "Normal", category = "Folds", keys = "zM", desc = "Close all folds" },
  { mode = "Normal", category = "Folds", keys = "zR", desc = "Open all folds" },

  -- Command
  { mode = "Command", category = "Command", keys = ":w", desc = "Save file" },
  { mode = "Command", category = "Command", keys = ":q", desc = "Quit" },
  { mode = "Command", category = "Command", keys = ":wq", desc = "Save and quit" },
  { mode = "Command", category = "Command", keys = ":x", desc = "Save and quit" },
  { mode = "Command", category = "Command", keys = ":e", desc = "Edit file" },
  { mode = "Command", category = "Command", keys = ":%s/old/new/g", desc = "Find and replace" },

  -- LSP
  { mode = "Normal", category = "LSP", keys = "gD", desc = "Go to declaration" },
  { mode = "Normal", category = "LSP", keys = "gI", desc = "Go to implementation" },
  { mode = "Normal", category = "LSP", keys = "gK", desc = "Signature help" },
  { mode = "Normal", category = "LSP", keys = "K", desc = "Hover doc" },
  { mode = "Normal", category = "LSP", keys = "gd", desc = "Go to definition" },
  { mode = "Normal", category = "LSP", keys = "gr", desc = "Go to references" },
  { mode = "Normal", category = "LSP", keys = "gy", desc = "Go to type definition" },
  { mode = "Normal", category = "LSP", keys = "<leader>ca", desc = "Code action" },
  { mode = "Normal", category = "LSP", keys = "<leader>cd", desc = "Line diagnostics" },
  { mode = "Normal", category = "LSP", keys = "<leader>cf", desc = "Format document" },
  { mode = "Normal", category = "LSP", keys = "<leader>cr", desc = "Rename symbol" },
  { mode = "Normal", category = "LSP", keys = "[d", desc = "Previous diagnostic" },
  { mode = "Normal", category = "LSP", keys = "]d", desc = "Next diagnostic" },
  { mode = "Normal", category = "LSP", keys = "[e", desc = "Previous error" },
  { mode = "Normal", category = "LSP", keys = "]e", desc = "Next error" },
  { mode = "Normal", category = "LSP", keys = "[w", desc = "Previous warning" },
  { mode = "Normal", category = "LSP", keys = "]w", desc = "Next warning" },

  -- Buffers
  { mode = "Normal", category = "Buffers", keys = "<leader>bb", desc = "Switch buffers" },
  { mode = "Normal", category = "Buffers", keys = "<leader>bd", desc = "Delete buffer" },
  { mode = "Normal", category = "Buffers", keys = "<leader>bo", desc = "Close other buffers" },
  { mode = "Normal", category = "Buffers", keys = "[b", desc = "Previous buffer" },
  { mode = "Normal", category = "Buffers", keys = "]b", desc = "Next buffer" },
  { mode = "Normal", category = "Buffers", keys = "<S-h>", desc = "Previous buffer" },
  { mode = "Normal", category = "Buffers", keys = "<S-l>", desc = "Next buffer" },

  -- Windows
  { mode = "Normal", category = "Windows", keys = "<C-h>", desc = "Navigate window left" },
  { mode = "Normal", category = "Windows", keys = "<C-j>", desc = "Navigate window down" },
  { mode = "Normal", category = "Windows", keys = "<C-k>", desc = "Navigate window up" },
  { mode = "Normal", category = "Windows", keys = "<C-l>", desc = "Navigate window right" },
  { mode = "Normal", category = "Windows", keys = "<C-Up>", desc = "Resize window up" },
  { mode = "Normal", category = "Windows", keys = "<C-Down>", desc = "Resize window down" },
  { mode = "Normal", category = "Windows", keys = "<C-Left>", desc = "Resize window left" },
  { mode = "Normal", category = "Windows", keys = "<C-Right>", desc = "Resize window right" },
  { mode = "Normal", category = "Windows", keys = "<leader>w-", desc = "Split window below" },
  { mode = "Normal", category = "Windows", keys = "<leader>w|", desc = "Split window right" },
  { mode = "Normal", category = "Windows", keys = "<leader>wd", desc = "Delete window" },
  { mode = "Normal", category = "Windows", keys = "<leader>wm", desc = "Maximize window toggle" },

  -- Tabs
  { mode = "Normal", category = "Tabs", keys = "<leader><tab><tab>", desc = "New tab" },
  { mode = "Normal", category = "Tabs", keys = "<leader><tab>[", desc = "Previous tab" },
  { mode = "Normal", category = "Tabs", keys = "<leader><tab>]", desc = "Next tab" },
  { mode = "Normal", category = "Tabs", keys = "<leader><tab>d", desc = "Close tab" },
  { mode = "Normal", category = "Tabs", keys = "<leader><tab>l", desc = "Last tab" },
  { mode = "Normal", category = "Tabs", keys = "<leader><tab>o", desc = "Close other tabs" },

  -- Git
  { mode = "Normal", category = "Git", keys = "<leader>gB", desc = "Git browse" },
  { mode = "Normal", category = "Git", keys = "<leader>gb", desc = "Git blame line" },
  { mode = "Normal", category = "Git", keys = "<leader>gf", desc = "Lazygit current file" },
  { mode = "Normal", category = "Git", keys = "<leader>gg", desc = "Lazygit" },
  { mode = "Normal", category = "Git", keys = "<leader>ghD", desc = "Diff this ~" },
  { mode = "Normal", category = "Git", keys = "<leader>ghR", desc = "Reset buffer" },
  { mode = "Normal", category = "Git", keys = "<leader>ghS", desc = "Stage buffer" },
  { mode = "Normal", category = "Git", keys = "<leader>ghd", desc = "Diff this" },
  { mode = "Normal", category = "Git", keys = "<leader>ghp", desc = "Preview hunk" },
  { mode = "Normal", category = "Git", keys = "<leader>ghr", desc = "Reset hunk" },
  { mode = "Normal", category = "Git", keys = "<leader>ghs", desc = "Stage hunk" },
  { mode = "Normal", category = "Git", keys = "<leader>gl", desc = "Lazygit log" },
  { mode = "Normal", category = "Git", keys = "<leader>gs", desc = "Git status" },
  { mode = "Normal", category = "Git", keys = "[h", desc = "Previous hunk" },
  { mode = "Normal", category = "Git", keys = "]h", desc = "Next hunk" },

  -- Picker
  { mode = "Normal", category = "Picker", keys = "<leader>s\"", desc = "Registers" },
  { mode = "Normal", category = "Picker", keys = "<leader>sC", desc = "Commands" },
  { mode = "Normal", category = "Picker", keys = "<leader>sD", desc = "Workspace diagnostics" },
  { mode = "Normal", category = "Picker", keys = "<leader>sH", desc = "Highlight groups" },
  { mode = "Normal", category = "Picker", keys = "<leader>sM", desc = "Man pages" },
  { mode = "Normal", category = "Picker", keys = "<leader>sR", desc = "Resume" },
  { mode = "Normal", category = "Picker", keys = "<leader>sS", desc = "Workspace symbols" },
  { mode = "Normal", category = "Picker", keys = "<leader>sT", desc = "Todo/Fix/Fixme" },
  { mode = "Normal", category = "Picker", keys = "<leader>sa", desc = "Autocmds" },
  { mode = "Normal", category = "Picker", keys = "<leader>sc", desc = "Command history" },
  { mode = "Normal", category = "Picker", keys = "<leader>sd", desc = "Document diagnostics" },
  { mode = "Normal", category = "Picker", keys = "<leader>sh", desc = "Help pages" },
  { mode = "Normal", category = "Picker", keys = "<leader>sj", desc = "Jumplist" },
  { mode = "Normal", category = "Picker", keys = "<leader>sk", desc = "Keymaps" },
  { mode = "Normal", category = "Picker", keys = "<leader>sl", desc = "Location list" },
  { mode = "Normal", category = "Picker", keys = "<leader>sm", desc = "Marks" },
  { mode = "Normal", category = "Picker", keys = "<leader>sq", desc = "Quickfix list" },
  { mode = "Normal", category = "Picker", keys = "<leader>sr", desc = "Resume picker" },
  { mode = "Normal", category = "Picker", keys = "<leader>ss", desc = "Document symbols" },
  { mode = "Normal", category = "Picker", keys = "<leader>st", desc = "Todo comments" },
  { mode = "Normal", category = "Picker", keys = "<leader>sw", desc = "Grep word" },
  { mode = "Normal", category = "Picker", keys = "<leader>sg", desc = "Live grep" },
  { mode = "Normal", category = "Picker", keys = "<leader>fb", desc = "Find buffers" },
  { mode = "Normal", category = "Picker", keys = "<leader>fc", desc = "Find config files" },
  { mode = "Normal", category = "Picker", keys = "<leader>ff", desc = "Find files" },
  { mode = "Normal", category = "Picker", keys = "<leader>fg", desc = "Live grep" },
  { mode = "Normal", category = "Picker", keys = "<leader>fr", desc = "Recent files" },

  -- File Explorer
  { mode = "Normal", category = "File Explorer", keys = "<leader>E", desc = "Toggle neo-tree cwd" },
  { mode = "Normal", category = "File Explorer", keys = "<leader>be", desc = "Buffer explorer" },
  { mode = "Normal", category = "File Explorer", keys = "<leader>e", desc = "Toggle neo-tree root" },
  { mode = "Normal", category = "File Explorer", keys = "<leader>fE", desc = "Toggle neo-tree cwd" },
  { mode = "Normal", category = "File Explorer", keys = "<leader>fe", desc = "Toggle neo-tree root" },
  { mode = "Normal", category = "File Explorer", keys = "<leader>ge", desc = "Git explorer" },

  -- Terminal
  { mode = "Normal", category = "Terminal", keys = "<C-/>", desc = "Toggle terminal" },
  { mode = "Normal", category = "Terminal", keys = "<leader>fT", desc = "Floating terminal cwd" },
  { mode = "Normal", category = "Terminal", keys = "<leader>ft", desc = "Floating terminal root" },
  { mode = "Terminal", category = "Terminal", keys = "<C-/>", desc = "Toggle terminal" },

  -- Diagnostics / Trouble
  { mode = "Normal", category = "Diagnostics", keys = "<leader>xL", desc = "Location list (Trouble)" },
  { mode = "Normal", category = "Diagnostics", keys = "<leader>xQ", desc = "Quickfix list (Trouble)" },
  { mode = "Normal", category = "Diagnostics", keys = "<leader>xT", desc = "Todo/Fix/Fixme (Trouble)" },
  { mode = "Normal", category = "Diagnostics", keys = "<leader>xX", desc = "Buffer diagnostics (Trouble)" },
  { mode = "Normal", category = "Diagnostics", keys = "<leader>cs", desc = "Symbols outline" },
  { mode = "Normal", category = "Diagnostics", keys = "<leader>xt", desc = "Todo (Trouble)" },
  { mode = "Normal", category = "Diagnostics", keys = "<leader>xx", desc = "Workspace diagnostics (Trouble)" },
  { mode = "Normal", category = "Diagnostics", keys = "[t", desc = "Previous todo comment" },
  { mode = "Normal", category = "Diagnostics", keys = "]t", desc = "Next todo comment" },
}

return M
